### ISSUE TITLE
Specifying us-east-1 as a region does not work correctly

### ISSUE THREAD

**Issue by liwadman** [stephenbradshaw/aws_url_signer#1]
Some services don't have a region in their domain name - like, IAM, that are in us-east-1. 

Other services, like EKS have a us-east-1 domain like 'eks.us-east-1.amazonaws.com'

if I specify a region to a service like EKS, the tool incorrectly returns a domain without a region.

For more information about which services have a global/general endpoint, check this doc: https://docs.aws.amazon.com/general/latest/gr/rande.html

The intended behavior should be everything except the mentioned services go to servicename.region.amazonaws.com

**Comment by stephenbradshaw** [comment]
Thanks for reporting. Turns out my logic for handling global API endpoints was completely wrong. Have updated. Hopefully its now fixed, let me know how you go.

**Comment by stephenbradshaw** [comment]
Believe this is fixed so closing, let me know if not and I'll reevaluate
